import Link from "next/link";
import styles from "./landing.module.css";
const receipt = "https://explorer.solana.com/tx/5qRPZVjqCoRGyJqAKSRL9owHSTmZavnAeHuK76vdGESafiKDPzPdd4Ktg2sMEnnHVysiKjdnqxuhbCmduXgLMWMy?cluster=devnet";
export default function Home() {
  return <main className={styles.frame}><div className={styles.shell}>
    <header className={styles.header}><Link href="/" className="wordmark" aria-label="AfterHours home">AFTER<span>HOURS</span><i /></Link><span className={styles.headerNote}>A SERV decision desk</span><Link href="/workspace" className={styles.navAction}>Open Review Desk <span aria-hidden="true">↗</span></Link></header>
    <section className={styles.hero}><div className={styles.heroText}><h1>Same market.<br />Different intent.<br /><em>Better next step.</em></h1><p>When the reference is uncertain, the full trade isn’t the only choice. Tell SERV what matters to you. Compare your request, a smaller permitted trade, and waiting.</p><Link className={styles.primary} href="/workspace">Compare a request <span aria-hidden="true">↗</span></Link><span className={styles.disclosure}>Devnet test tokens · No wallet required for review</span></div>
      <figure className={styles.sheet}><figcaption><span>AfterHours / decision study</span><span>Illustrative comparison</span></figcaption><div className={styles.studyInput}><span>Proposed request</span><strong>100 <small>USDC-test</small></strong><p>Carried simulated reference</p></div><div className={styles.studyChoices}><span>Requested<br /><strong>100</strong></span><span>Reduced<br /><strong>50</strong></span><span>Wait<br /><strong>0</strong></span></div><div className={styles.intentRows}><div><p>“Full amount only.<br />Otherwise, wait.”</p><strong>Wait</strong></div><div><p>“A smaller permitted<br />trade is acceptable.”</p><strong>Reduce</strong></div></div><p className={styles.sheetNote}>Intent guides the choice. Evidence limits the options. Run a review to obtain an actual validated plan.</p></figure>
    </section>
    <section className={styles.method} id="how-it-works"><div className={styles.sectionTitle}><h2>From a request<br />to a reasoned choice.</h2><p>SERV interprets your intent. Exact calculations stay in deterministic tools, and the application validates the chosen option against one dated observation.</p></div><ol className={styles.sequence}><li><span>01 / INTENT</span><h3>Set your terms.</h3><p>Choose an amount and a simulated reference scenario. Say whether size, participation, or waiting matters most.</p></li><li><span>02 / EVIDENCE</span><h3>Gather the facts.</h3><p>Read devnet reserve accounts. Calculate the interface cap, fixed-fee quote, minimum output, and feasibility for every alternative.</p></li><li className={styles.servStep}><span>03 / SERV</span><h3>Compare the choices.</h3><p>SERV uses a read-only tool and interprets your intent to choose among the requested trade, reduced trade, and waiting.</p></li><li><span>04 / VALIDATION</span><h3>Check the plan.</h3><p>Check the option, cited evidence, feasibility, and expiry. Missing reserves or paused policy leave waiting as the feasible path.</p></li></ol></section>
    <section className={styles.proof}><div><h2>See what changes<br />when your terms do.</h2><p>The clearest test: keep 100 USDC-test and the carried reference fixed. Review “full amount or wait,” then “a smaller trade is acceptable.” Inspect the alternatives, selected plan, evidence, actual tool calls, usage, and latency.</p><Link className={styles.primary} href="/workspace">Try the intent comparison <span aria-hidden="true">↗</span></Link></div><div className={styles.proofRecord}><h3>A record you can inspect.</h3><ul><li>One observation shared by all options</li><li>Quote and minimum output calculated by tools</li><li>Application checks shown beside the plan</li><li>Actual completion and tool-call provenance</li></ul><p>Validation checks structure and feasibility. It does not prove every model sentence is true. The explanation remains advisory.</p><details><summary>Historical pool settlement evidence</summary><p>A script-signed devnet swap was verified. It proves direct SPL Token Swap v3 settlement only; browser-wallet settlement remains unverified.</p><a href={receipt} target="_blank" rel="noreferrer">View the script receipt ↗</a></details></div></section>
    <footer className={styles.footer}><div><Link href="/" className="wordmark">AFTER<span>HOURS</span><i /></Link><p>Uncertainty, made visible.</p></div><p>Built with SERV and Solana devnet. USDC-test and AAPLX-test are test SPL tokens, not backed shares. References are simulated: no live or signed Pyth data. No active on-chain AfterHours guard; the interface policy can be bypassed by direct pool calls.</p><Link href="/workspace">Review Desk ↗</Link></footer>
  </div></main>;
}
